# Static Defaults
replicaCount: 1
image:
  repository: 'nexus3.o-ran-sc.org:10002/o-ran-sc'
  name: nonrtric-o-ru-closed-loop-recovery
  tag: 1.0.0
  pullPolicy: IfNotPresent

service:
  type: NodePort
  ports:
    port: 830
    nodePort: 30835

simulators:
  - simRu: o-ru-11221.simulators
    simDu: o-du-1122.simulators

conf:
  mrHost: http://message-router.onap
  mrPort: 3904
  sdnrHost: https://sdnc.onap
  sdnrPort: 8443
  verbose: on
 
