# Static Defaults
image:
  repository: 'nexus3.o-ran-sc.org:10002/o-ran-sc'
  name: a1-simulator
  tag: 2.2.0
#  pullPolicy: IfNotPresent
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  ports:
    httpPort: 8085
    httpsPort: 8185

a1Sims:
  - name: a1-sim-osc-0
    a1Version: OSC_2.1.0
    allowHttp: true

  - name: a1-sim-osc-1
    a1Version: OSC_2.1.0
    allowHttp: true

  - name: a1-sim-std-0
    a1Version: STD_1.1.3
    allowHttp: true

  - name: a1-sim-std-1
    a1Version: STD_1.1.3
    allowHttp: true

  - name: a1-sim-std2-0
    a1Version: STD_2.0.0
    allowHttp: true

  - name: a1-sim-std2-1
    a1Version: STD_2.0.0
    allowHttp: true
